---
title: "BSA3"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{BSA2}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  eval=FALSE
)
```

# reduction in code from 8129 characters to 4860 characters. That includes 
# comments, spaces, headings, etc

```{r setup}
library(BSA)
library(tidyverse)
library(foreach)
library(GenomicRanges)
library(BSgenome.CneoformansVarGrubiiKN99.NCBI.ASM221672v1)

kn99_genome = BSgenome.CneoformansVarGrubiiKN99.NCBI.ASM221672v1
```

# Read in data from VCF and parse into dataframe

```{r}
chr_map = tibble(seqnames = seqnames(kn99_genome), 
                 CHR=c(seq(1:14), "M"))

input_paths = list(
  bsa6_vcf = "/mnt/scratch/variant_calling_pipeline/bsa/results_bsa6/variant_calling/bwamem2/vcftools/group_1_merged_dusted.recode.vcf", #system.file("BSA6.IGV.vcf.gz", package="BSA"),
  bsa6_meta = system.file("bsa6_samplesheet.rds", package="BSA")
)

meta_df = readRDS(input_paths$bsa6_meta)

tmp_dir = tempdir()
raw_samples_df = vcf_to_qtlseqr_table(input_paths$bsa6_vcf, "~/Desktop", 
                                      parent_ref_sample = 'KN99a', 
                                      parent_alt_sample = 'TDY1993',
                                      parent_filter = FALSE) 

samples_df = raw_samples_df %>% 
  left_join(chr_map) %>% 
  select(c("seqnames", colnames(raw_samples_df)[2:length(raw_samples_df)])) %>%
  dplyr::rename(CHR = seqnames) %>% 
  filter(!is.na(CHR)) %>%
  arrange(sample, CHR, POS) %>% 
  left_join(meta_df) %>%
  # note this!
  mutate(bulk = ifelse(cond == "inoculum", "low", "high"))

samples_df = raw_samples_df %>% 
  left_join(chr_map) %>% 
  arrange(sample, CHR, POS) %>% 
  left_join(meta_df) %>%
  # note this!
  mutate(bulk = ifelse(cond == "inoculum", "low", "high"))
```
